### PR TITLE
Fix isBrowser

### LINKED ISSUE #10: isBrowser returns false in the browser
Hi @Koleok,

I'm working on a new project and I don't know why but in the browser I have a `process` object declared. It seems to be something added by Node. (I'm using v4.6.1)

screenshot

Because of that, our [isBrowser](https://github.com/samybob1/meteor-redux-middlewares/blob/master/src/utils.js#L26) function returns false. Then because of [this bug](https://github.com/meteor/react-packages/issues/99), as we are not running Tracker inside setImmediate, my subscriptions stay on the "not ready" state.

We have to improve the isBrowser function, what do you think about [this solution](http://stackoverflow.com/a/31090240/6917588)?

```js
export const isBrowser = () => {
  try {
    return this === window;
  } catch (e) {
    return false;
  }
};
```

### PR DESCRIPTION
**Pull request by samybob1**
Fixes #10

### CODE REVIEW

File: src/runContextual.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ export default run => {
   if (isBrowser()) {
     // setTimeout is fixing this bug:
     // https://github.com/meteor/react-packages/issues/99
-    setImmediate(run);
+    setTimeout(run, 0);
```
Comment (samybob1) [inline src/runContextual.js]: With the new `isBrowser` function, I had this error:

>ReferenceError: setImmediate is not defined

File: src/utils.js [hunk 2]
```diff
@@ -23,8 +23,12 @@ export const createAction =
...
   (tracker, middlewares) => middlewares.map(m => m(tracker));
 
-export const isBrowser =
-  () => typeof process === 'undefined';
+export const isBrowser = () =>
+  typeof process === 'undefined' || (
+    typeof process === 'object' &&
+    typeof process.versions === 'object' &&
+    typeof process.versions.node === 'undefined'
+  );
```
Comment (samybob1) [inline src/utils.js]: I used [this solution](http://stackoverflow.com/a/31456668/6917588) 😉

Comment (Koleok) [inline src/utils.js]: that works! pretty bullet-proof that way

File: src/runContextual.js (hunk 1 above)
Comment (Koleok) [inline src/runContextual.js]: Hmm, I am not sure why that is but no biggie i guess, you can skip adding the `0` as [second arg since it is the default](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout)

Comment (samybob1) [inline src/runContextual.js]: You're right!
