### PR TITLE
Stop previous subscription synchronously

### LINKED ISSUE #11: Start subscription sometimes not working
Sometimes, the `startSubscription` action was dispatched but the subscription was never on the `ready` state. After 6 hours, I finally found out what was going on! 🎉 

Inside the subscription middleware, [we are dispatching a `STOP_SUBSCRIPTION` action](https://github.com/samybob1/meteor-redux-middlewares/blob/master/src/subscriptions.js#L58) because we don't want a subscription to be started twice at the same time, but sometimes the actions are processed this way:

* Start a subscription
* The subscription was already started, so we dispatch a `STOP_SUBSCRIPTION` action
* First `Tracker` run, the subscription is not ready yet
* **We accidentally stop the new subscription while trying to stop the previous one**

While we were expecting this:

* Start a subscription
* The subscription was already started, so we dispatch a `STOP_SUBSCRIPTION` action
* **The previous subscription is stopped as expected**
* First `Tracker` run, the subscription is not ready yet
* Second run, the subscription is ready, we dispatch a `_SUBSCRIPTION_CHANGED` action

I fixed that, I will send a PR!

### PR DESCRIPTION
**Pull request by samybob1**
Fixes #11

### CODE REVIEW

File: src/subscriptions.js [hunk 1]
```diff
@@ -18,6 +17,18 @@ import {
...
 
+const stopSubscription = action => {
+  if (subscriptions[action.payload]) {
+    const subscriptionId = subscriptions[action.payload].subscriptionId;
+
+    computations[subscriptionId].stop();
+    subscriptions[action.payload].stop();
+
+    delete computations[subscriptionId];
+    delete subscriptions[action.payload];
```
Comment (Koleok) [inline src/subscriptions.js]: Might be less extreme to do 
```javascript
computations[subscriptionId] = undefined;
subscriptions[action.payload] = undefined;
```

Though I don't really see a problem with what you did here other than my personal rule agains the `delete` keyword haha

**Comment by Koleok** [comment]
@samybob1 Nice thinking on this!
